### ISSUE TITLE
Intrinsic Rewards

### ISSUE THREAD

**Issue by robjlyons** [danijar/dreamerv2#14]
Is it possible to add the use of intrinsic rewards to this method?

Thanks

**Comment by danijar** [comment]
Plan2Explore is implemented in this code base via `--expl_behavior plan2explore`. The task policy will still be trained on the rewards from the environment but it will only be used for computing eval scores and not for data collection. You can also set `--expl_until 1e6` if you want to switch to collecting data via the task policy after 1M steps. By default, the exploration policy uses no external rewards, but there is a config for that, too. Check out the exploration section in `configs.yaml`.

**Comment by mjlbach** [comment]
Hi @danijar,

Was this option removed at some point (it doesn't seem so from the git history)? I was confused because I grep'd the codebase and say no mention of plan2explore in the arg parsing, the closet thing being the conditional for `if not greedy` [here](https://github.com/danijar/dreamerv2/blob/e02ceb9a77596e695a66d099e749b6bdf62db50e/dreamerv2/agent.py#L66-L69)


Running

```
 python dreamerv2/train.py --logdir ~/logdir/atari_pong/dreamerv2/1 --expl_behavior plan2explore --configs atari --task atari_pong
```
Yields:

```
Decoder MLP outputs: []
Traceback (most recent call last):
  File "/home/michael/Repositories/lab/dreamerv2/dreamerv2/train.py", line 196, in <module>
    main()
  File "/home/michael/Repositories/lab/dreamerv2/dreamerv2/train.py", line 154, in main
    agnt = agent.Agent(config, obs_space, act_space, step)
  File "/home/michael/Repositories/lab/dreamerv2/dreamerv2/agent.py", line 21, in __init__
    self._expl_behavior = getattr(expl, config.expl_behavior)(
AttributeError: module 'expl' has no attribute 'plan2explore'
```
