### ISSUE TITLE
replay data memory usage?

### ISSUE THREAD

**Issue by tominku** [danijar/dreamerv2#40]
Hi, thank you for the good code base.
I just wonder if a normal PC can embrace all the replay data in the memory when the agent step goes over 1 million. If I have about 16 GB memory, then can this agent be trained until the end?
It seems like the replay data size keep increasing as the training proceeds (without a truncation). Do you have any idea that the agent can be trained in a small-sized memory?
Thanks!

**Comment by danijar** [comment]
Hi, 1M frames should take slightly less than 12GB so it depends how much additional RAM is needed by your environment(s). You can of course always reduce the replay capacity or image size to reduce RAM usage. I computed the 12GB as 64x64x3 pixels x 1 byte (uint8) x 1e6 steps / 1024^3 = 11.4 GB, since the images dominate the replay buffer.

**Comment by ManuelRios18** [comment]
@danijar Hello, I am still reading the paper so I haven't deep into the code very carefully, but I would like to ask.

Approximately, How long does it take to train in a regular PC? 

I am planning to extend this framework to the multiagent setting and I am afraid of the computation times.
