### ISSUE TITLE
TypeError: unsupported operand type(s) for //=: 'str' and 'int'

### ISSUE THREAD

**Issue by Luffffffy** [danijar/dreamerv2#5]
I ran this code

python dreamer.py --logdir ~/logdir/atari_pong/dreamerv2/1 --configs defaults atari --task atari_pong

But I got this mistake

**Comment by danijar** [comment]
Can you post the traceback, please?

**Comment by Luffffffy** [comment]
It seems that the problem is this line of code

`config.steps //= config.action_repeat`

![image](https://user-images.githubusercontent.com/49063302/115173633-4a139e80-a0fa-11eb-8a41-0a6a016aa0e0.png)

**Comment by danijar** [comment]
It looks like `config.steps` is a string for some reason, either because how the configs file is read or how the flags are parsed. My guess is that this could be specific to Windows, because I have never seen this problem on Linux. Unfortunately, I don't have the capacity to support Windows. If you find a solution, please comment here so other people can benefit from it.
